name: ci-test

on:
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Copy Site recursively to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "out/*"
          target: "domains/test.xn--4lj4bfp6d.eu.org/public_html"
          strip_components: 1
          rm: true
          debug: true

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_PORT: ${{ secrets.PORT }}

      - name: Copy htaccess to site
        run: ssh staging "cd ~/domains/test.xn--4lj4bfp6d.eu.org/homes/; cp .htaccess ../public_html/"

      - name: Add symlink to the logs
        run: ssh staging "cd ~/domains/test.xn--4lj4bfp6d.eu.org/public_html/; ln -s ../logs logs"